aws:
  region: us-east-1
  accessKeyId: !!null
  secretAccessKey: !!null
db:
  imageTableName: images
  connectionTableName: connections
images:
  bucket: !!null
websocket:
  apiId: !!null
stage: dev
